" DO NOT EDIT THIS FILE
" Add your own customizations in ~/.vim_runtime/my_configs.vim

source ~/.vim_liuyf/basic.vim
source ~/.vim_liuyf/plug.vim

lua << EOF
require'lspconfig'.solargraph.setup{}
require'lspconfig'.tsserver.setup{}
require'lspconfig'.gopls.setup{}
EOF

lua require('lspfuzzy').setup {}

"set runtimepath+=~/.vim_runtime
"
"source ~/.vim_runtime/vimrcs/basic.vim
"source ~/.vim_runtime/vimrcs/filetypes.vim
"source ~/.vim_runtime/vimrcs/plugins_config.vim
"source ~/.vim_runtime/vimrcs/extended.vim
"try
"  source ~/.vim_runtime/my_configs.vim
"catch
"endtry
